const dummyProblemsData = [
  {
    _id: "prob_001",
    slug: "sum-of-two-numbers",
    title: "Sum of Two Numbers",
    statement: "Given two integers A and B, output their sum.",
    input_format: "Two integers A and B separated by space.",
    output_format: "Print a single integer — A + B.",
    constraints: "−10^9 ≤ A, B ≤ 10^9",
    samples: [{ input: "2 3", output: "5", explanation: "2 + 3 = 5" }],
    time_limit_ms: 1000,
    memory_limit_kb: 65536,
    tags: ["math", "implementation"],
    difficulty: "easy",
    createdBy: "admin",
    createdAt: "2026-02-25T00:00:00.000Z",
    solvedCount: 1245,
    acceptanceRate: 0.86,
    hiddenTestcaseCount: 10,
  },
  {
    _id: "prob_002",
    slug: "reverse-string",
    title: "Reverse a String",
    statement: "Given a string S, print the string reversed.",
    input_format: "A single line containing string S (length ≤ 10^5).",
    output_format: "A single line with S reversed.",
    constraints: "S contains printable ASCII characters. 1 ≤ |S| ≤ 100000",
    samples: [
      {
        input: "hello",
        output: "olleh",
        explanation: "reverse of 'hello' is 'olleh'",
      },
    ],
    time_limit_ms: 1000,
    memory_limit_kb: 131072,
    tags: ["strings", "implementation"],
    difficulty: "easy",
    createdBy: "editor_jane",
    createdAt: "2026-02-20T12:00:00.000Z",
    solvedCount: 980,
    acceptanceRate: 0.78,
    hiddenTestcaseCount: 8,
  },
  {
    _id: "prob_003",
    slug: "two-sum-closest",
    title: "Two Sum Closest",
    statement:
      "Given an array of N integers and an integer X, find two distinct elements whose sum is closest to X. Output their indices (1-based). If multiple answers exist, output any.",
    input_format: "First line: N X.\n Second line: N integers A1 A2 ... AN.",
    output_format: "Two integers i j (1 ≤ i < j ≤ N).",
    constraints: "2 ≤ N ≤ 2*10^5, |Ai| ≤ 10^9, |X| ≤ 10^9",
    samples: [
      {
        input: "5 10\n1 4 6 8 3",
        output: "2 4",
        explanation:
          "A2 + A4 = 4 + 8 = 12 (closest to 10). Another valid answer could be 1 4.",
      },
    ],
    time_limit_ms: 2000,
    memory_limit_kb: 262144,
    tags: ["two-pointers", "sorting", "arrays"],
    difficulty: "medium",
    createdBy: "coach_ali",
    createdAt: "2026-01-30T08:30:00.000Z",
    solvedCount: 430,
    acceptanceRate: 0.52,
    hiddenTestcaseCount: 20,
  },
  {
    _id: "prob_004",
    slug: "balanced-parentheses",
    title: "Balanced Parentheses",
    statement:
      "Given a string of brackets consisting of '(' and ')', determine whether the string is balanced. A string is balanced if every opening bracket has a corresponding closing bracket in the correct order.",
    input_format: "Single string S of length up to 10^6.",
    output_format: "Print YES if balanced, otherwise NO.",
    constraints: "1 ≤ |S| ≤ 10^6",
    samples: [
      {
        input: "()()()",
        output: "YES",
        explanation: "Every opening bracket matches correctly.",
      },
      { input: "(()", output: "NO", explanation: "One '(' is unmatched." },
    ],
    time_limit_ms: 1000,
    memory_limit_kb: 65536,
    tags: ["stack", "strings"],
    difficulty: "easy",
    createdBy: "editor_jane",
    createdAt: "2026-02-10T09:00:00.000Z",
    solvedCount: 1500,
    acceptanceRate: 0.92,
    hiddenTestcaseCount: 12,
  },
  {
    _id: "prob_005",
    slug: "shortest-path-grid",
    title: "Shortest Path in Grid",
    statement:
      "Given an R×C grid with '.' (free) and '#' (blocked), find the minimum number of steps from start (sr, sc) to target (tr, tc). You may move up/down/left/right. If unreachable print -1.",
    input_format:
      "First line: R C. Next R lines: grid rows. Next line: sr sc tr tc (1-based indices).",
    output_format: "Single integer — minimum steps or -1.",
    constraints: "1 ≤ R, C ≤ 1000",
    samples: [
      {
        input: "3 3\n...\n.#.\n...\n1 1 3 3",
        output: "4",
        explanation: "One shortest path length is 4 steps.",
      },
    ],
    time_limit_ms: 2000,
    memory_limit_kb: 262144,
    tags: ["bfs", "graphs", "grid"],
    difficulty: "medium",
    createdBy: "coach_ali",
    createdAt: "2026-02-15T14:45:00.000Z",
    solvedCount: 300,
    acceptanceRate: 0.48,
    hiddenTestcaseCount: 25,
  },
  {
    _id: "prob_006",
    slug: "count-inversions",
    title: "Count Inversions",
    statement:
      "Given an array of N integers, count the number of inversions (pairs i<j such that Ai > Aj).",
    input_format: "First line: N. Second line: N integers.",
    output_format: "Single integer — number of inversions.",
    constraints:
      "1 ≤ N ≤ 2*10^5, |Ai| ≤ 10^9. Answer fits in 64-bit signed integer.",
    samples: [
      {
        input: "5\n2 3 8 6 1",
        output: "5",
        explanation: "Inversions are (2,1),(3,1),(8,6),(8,1),(6,1).",
      },
    ],
    time_limit_ms: 2000,
    memory_limit_kb: 262144,
    tags: ["divide-and-conquer", "fenwick", "sorting"],
    difficulty: "hard",
    createdBy: "admin",
    createdAt: "2026-01-12T18:00:00.000Z",
    solvedCount: 95,
    acceptanceRate: 0.21,
    hiddenTestcaseCount: 30,
  },
  {
    _id: "prob_007",
    slug: "merge-k-sorted-lists",
    title: "Merge K Sorted Lists",
    statement:
      "Given k sorted linked lists, merge them into one sorted list and output its elements.",
    input_format:
      "First line: k. Next lines: each line starts with ni followed by ni integers for the i-th list.",
    output_format: "Single line with merged sorted values separated by spaces.",
    constraints: "1 ≤ k ≤ 10^4, sum of all ni ≤ 2*10^5",
    samples: [
      {
        input: "3\n3 1 4 5\n2 1 3\n3 2 6 7",
        output: "1 1 2 3 4 5 6 7",
        explanation: "Merged sorted order.",
      },
    ],
    time_limit_ms: 2000,
    memory_limit_kb: 262144,
    tags: ["heaps", "linked-list", "priority-queue"],
    difficulty: "medium",
    createdBy: "editor_maria",
    createdAt: "2026-02-05T10:20:00.000Z",
    solvedCount: 210,
    acceptanceRate: 0.55,
    hiddenTestcaseCount: 18,
  },
  {
    _id: "prob_008",
    slug: "matrix-chain-multiplication",
    title: "Matrix Chain Multiplication",
    statement:
      "Given dimensions of matrices, compute minimum number of scalar multiplications needed to multiply the chain.",
    input_format:
      "First line: n (number of matrices). Second line: n+1 integers p0 p1 ... pn where matrix i has dimensions pi-1 x pi.",
    output_format: "Single integer — minimum multiplication cost.",
    constraints: "1 ≤ n ≤ 500",
    samples: [
      {
        input: "3\n10 20 30 40",
        output: "18000",
        explanation: "Optimal parenthesization cost is 18000.",
      },
    ],
    time_limit_ms: 2000,
    memory_limit_kb: 262144,
    tags: ["dp", "optimization"],
    difficulty: "hard",
    createdBy: "prof_khan",
    createdAt: "2026-01-05T07:00:00.000Z",
    solvedCount: 60,
    acceptanceRate: 0.14,
    hiddenTestcaseCount: 25,
  },
  {
    _id: "prob_009",
    slug: "longest-common-subsequence",
    title: "Longest Common Subsequence",
    statement:
      "Given two strings A and B, find the length of their longest common subsequence (LCS).",
    input_format: "Two lines: A and B. Length of A, B ≤ 2000.",
    output_format: "Single integer — length of LCS(A, B).",
    constraints: "1 ≤ |A|, |B| ≤ 2000",
    samples: [
      {
        input: "ABCBDAB\nBDCABA",
        output: "4",
        explanation: "One LCS is 'BCBA' (or 'BDAB', length 4).",
      },
    ],
    time_limit_ms: 2000,
    memory_limit_kb: 524288,
    tags: ["dp", "strings"],
    difficulty: "hard",
    createdBy: "prof_khan",
    createdAt: "2026-01-20T11:11:00.000Z",
    solvedCount: 120,
    acceptanceRate: 0.18,
    hiddenTestcaseCount: 28,
  },
  {
    _id: "prob_010",
    slug: "count-subarrays-with-sum",
    title: "Count Subarrays With Given Sum",
    statement:
      "Given an array of non-negative integers and an integer S, count the number of contiguous subarrays that sum to S.",
    input_format: "First line: N S. Second line: N integers (Ai ≥ 0).",
    output_format:
      "Single integer — number of contiguous subarrays with sum == S.",
    constraints: "1 ≤ N ≤ 2*10^5, 0 ≤ Ai ≤ 10^9, 0 ≤ S ≤ 10^18",
    samples: [
      {
        input: "5 5\n1 2 3 2 1",
        output: "2",
        explanation: "Subarrays [2,3] and [3,2] sum to 5.",
      },
    ],
    time_limit_ms: 2000,
    memory_limit_kb: 262144,
    tags: ["two-pointers", "prefix-sum", "arrays"],
    difficulty: "medium",
    createdBy: "editor_maria",
    createdAt: "2026-02-02T16:00:00.000Z",
    solvedCount: 340,
    acceptanceRate: 0.49,
    hiddenTestcaseCount: 22,
  },
];
export default dummyProblemsData;
